clear all;
mex -g -IC:\SIM\tm_algorithms -IC:\SIM\Projetos\TM300 ...
    -output turb_sf turb_sf.cpp ...
    C:\SIM\Projetos\TM300\tm_prop_turb.c ...
    C:\SIM\Projetos\TM300\tm_atmos.c ...
    C:\SIM\tm_algorithms\math_3space.c ...
    C:\SIM\tm_algorithms\math_wrap.c ...
    C:\SIM\tm_algorithms\math_atmos.c ...
    C:\SIM\tm_algorithms\math_util.c;
