// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: announcement.proto

package PluginAdapter.Api;

public final class AnnouncementOuterClass {
  private AnnouncementOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnnouncementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PluginAdapter.Api.Announcement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The adapter name uniquely identifies this adapter. Only one adapter is
     * allowed to connect with this name at a time.
     * It's useful to use this format: interface&#64;location. For example, if the
     * adapter is connected to the PRL42 System Under Test running at company Comp
     * and provides access to its SNMP interface, then the name would be
     * snmp&#64;prl42-comp.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * The adapter name uniquely identifies this adapter. Only one adapter is
     * allowed to connect with this name at a time.
     * It's useful to use this format: interface&#64;location. For example, if the
     * adapter is connected to the PRL42 System Under Test running at company Comp
     * and provides access to its SNMP interface, then the name would be
     * snmp&#64;prl42-comp.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Default configuration. All values should be set to their default values.
     * </pre>
     *
     * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
     * @return Whether the configuration field is set.
     */
    boolean hasConfiguration();
    /**
     * <pre>
     * Default configuration. All values should be set to their default values.
     * </pre>
     *
     * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
     * @return The configuration.
     */
    PluginAdapter.Api.ConfigurationOuterClass.Configuration getConfiguration();
    /**
     * <pre>
     * Default configuration. All values should be set to their default values.
     * </pre>
     *
     * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
     */
    PluginAdapter.Api.ConfigurationOuterClass.ConfigurationOrBuilder getConfigurationOrBuilder();

    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    java.util.List<PluginAdapter.Api.LabelOuterClass.Label> 
        getLabelsList();
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    PluginAdapter.Api.LabelOuterClass.Label getLabels(int index);
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    int getLabelsCount();
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    java.util.List<? extends PluginAdapter.Api.LabelOuterClass.LabelOrBuilder> 
        getLabelsOrBuilderList();
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    PluginAdapter.Api.LabelOuterClass.LabelOrBuilder getLabelsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Announcement of an adapter when it plugs in.
   * </pre>
   *
   * Protobuf type {@code PluginAdapter.Api.Announcement}
   */
  public static final class Announcement extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PluginAdapter.Api.Announcement)
      AnnouncementOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Announcement.newBuilder() to construct.
    private Announcement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Announcement() {
      name_ = "";
      labels_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Announcement();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PluginAdapter.Api.AnnouncementOuterClass.internal_static_PluginAdapter_Api_Announcement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PluginAdapter.Api.AnnouncementOuterClass.internal_static_PluginAdapter_Api_Announcement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PluginAdapter.Api.AnnouncementOuterClass.Announcement.class, PluginAdapter.Api.AnnouncementOuterClass.Announcement.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     * The adapter name uniquely identifies this adapter. Only one adapter is
     * allowed to connect with this name at a time.
     * It's useful to use this format: interface&#64;location. For example, if the
     * adapter is connected to the PRL42 System Under Test running at company Comp
     * and provides access to its SNMP interface, then the name would be
     * snmp&#64;prl42-comp.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The adapter name uniquely identifies this adapter. Only one adapter is
     * allowed to connect with this name at a time.
     * It's useful to use this format: interface&#64;location. For example, if the
     * adapter is connected to the PRL42 System Under Test running at company Comp
     * and provides access to its SNMP interface, then the name would be
     * snmp&#64;prl42-comp.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONFIGURATION_FIELD_NUMBER = 2;
    private PluginAdapter.Api.ConfigurationOuterClass.Configuration configuration_;
    /**
     * <pre>
     * Default configuration. All values should be set to their default values.
     * </pre>
     *
     * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
     * @return Whether the configuration field is set.
     */
    @java.lang.Override
    public boolean hasConfiguration() {
      return configuration_ != null;
    }
    /**
     * <pre>
     * Default configuration. All values should be set to their default values.
     * </pre>
     *
     * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
     * @return The configuration.
     */
    @java.lang.Override
    public PluginAdapter.Api.ConfigurationOuterClass.Configuration getConfiguration() {
      return configuration_ == null ? PluginAdapter.Api.ConfigurationOuterClass.Configuration.getDefaultInstance() : configuration_;
    }
    /**
     * <pre>
     * Default configuration. All values should be set to their default values.
     * </pre>
     *
     * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
     */
    @java.lang.Override
    public PluginAdapter.Api.ConfigurationOuterClass.ConfigurationOrBuilder getConfigurationOrBuilder() {
      return configuration_ == null ? PluginAdapter.Api.ConfigurationOuterClass.Configuration.getDefaultInstance() : configuration_;
    }

    public static final int LABELS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<PluginAdapter.Api.LabelOuterClass.Label> labels_;
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    @java.lang.Override
    public java.util.List<PluginAdapter.Api.LabelOuterClass.Label> getLabelsList() {
      return labels_;
    }
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends PluginAdapter.Api.LabelOuterClass.LabelOrBuilder> 
        getLabelsOrBuilderList() {
      return labels_;
    }
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    @java.lang.Override
    public int getLabelsCount() {
      return labels_.size();
    }
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    @java.lang.Override
    public PluginAdapter.Api.LabelOuterClass.Label getLabels(int index) {
      return labels_.get(index);
    }
    /**
     * <pre>
     * Labels that this adapter supports.
     * </pre>
     *
     * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
     */
    @java.lang.Override
    public PluginAdapter.Api.LabelOuterClass.LabelOrBuilder getLabelsOrBuilder(
        int index) {
      return labels_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (configuration_ != null) {
        output.writeMessage(2, getConfiguration());
      }
      for (int i = 0; i < labels_.size(); i++) {
        output.writeMessage(3, labels_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (configuration_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getConfiguration());
      }
      for (int i = 0; i < labels_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, labels_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PluginAdapter.Api.AnnouncementOuterClass.Announcement)) {
        return super.equals(obj);
      }
      PluginAdapter.Api.AnnouncementOuterClass.Announcement other = (PluginAdapter.Api.AnnouncementOuterClass.Announcement) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (hasConfiguration() != other.hasConfiguration()) return false;
      if (hasConfiguration()) {
        if (!getConfiguration()
            .equals(other.getConfiguration())) return false;
      }
      if (!getLabelsList()
          .equals(other.getLabelsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasConfiguration()) {
        hash = (37 * hash) + CONFIGURATION_FIELD_NUMBER;
        hash = (53 * hash) + getConfiguration().hashCode();
      }
      if (getLabelsCount() > 0) {
        hash = (37 * hash) + LABELS_FIELD_NUMBER;
        hash = (53 * hash) + getLabelsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PluginAdapter.Api.AnnouncementOuterClass.Announcement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Announcement of an adapter when it plugs in.
     * </pre>
     *
     * Protobuf type {@code PluginAdapter.Api.Announcement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PluginAdapter.Api.Announcement)
        PluginAdapter.Api.AnnouncementOuterClass.AnnouncementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PluginAdapter.Api.AnnouncementOuterClass.internal_static_PluginAdapter_Api_Announcement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PluginAdapter.Api.AnnouncementOuterClass.internal_static_PluginAdapter_Api_Announcement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PluginAdapter.Api.AnnouncementOuterClass.Announcement.class, PluginAdapter.Api.AnnouncementOuterClass.Announcement.Builder.class);
      }

      // Construct using PluginAdapter.Api.AnnouncementOuterClass.Announcement.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        configuration_ = null;
        if (configurationBuilder_ != null) {
          configurationBuilder_.dispose();
          configurationBuilder_ = null;
        }
        if (labelsBuilder_ == null) {
          labels_ = java.util.Collections.emptyList();
        } else {
          labels_ = null;
          labelsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PluginAdapter.Api.AnnouncementOuterClass.internal_static_PluginAdapter_Api_Announcement_descriptor;
      }

      @java.lang.Override
      public PluginAdapter.Api.AnnouncementOuterClass.Announcement getDefaultInstanceForType() {
        return PluginAdapter.Api.AnnouncementOuterClass.Announcement.getDefaultInstance();
      }

      @java.lang.Override
      public PluginAdapter.Api.AnnouncementOuterClass.Announcement build() {
        PluginAdapter.Api.AnnouncementOuterClass.Announcement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PluginAdapter.Api.AnnouncementOuterClass.Announcement buildPartial() {
        PluginAdapter.Api.AnnouncementOuterClass.Announcement result = new PluginAdapter.Api.AnnouncementOuterClass.Announcement(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(PluginAdapter.Api.AnnouncementOuterClass.Announcement result) {
        if (labelsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            labels_ = java.util.Collections.unmodifiableList(labels_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.labels_ = labels_;
        } else {
          result.labels_ = labelsBuilder_.build();
        }
      }

      private void buildPartial0(PluginAdapter.Api.AnnouncementOuterClass.Announcement result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.configuration_ = configurationBuilder_ == null
              ? configuration_
              : configurationBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PluginAdapter.Api.AnnouncementOuterClass.Announcement) {
          return mergeFrom((PluginAdapter.Api.AnnouncementOuterClass.Announcement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PluginAdapter.Api.AnnouncementOuterClass.Announcement other) {
        if (other == PluginAdapter.Api.AnnouncementOuterClass.Announcement.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasConfiguration()) {
          mergeConfiguration(other.getConfiguration());
        }
        if (labelsBuilder_ == null) {
          if (!other.labels_.isEmpty()) {
            if (labels_.isEmpty()) {
              labels_ = other.labels_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureLabelsIsMutable();
              labels_.addAll(other.labels_);
            }
            onChanged();
          }
        } else {
          if (!other.labels_.isEmpty()) {
            if (labelsBuilder_.isEmpty()) {
              labelsBuilder_.dispose();
              labelsBuilder_ = null;
              labels_ = other.labels_;
              bitField0_ = (bitField0_ & ~0x00000004);
              labelsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLabelsFieldBuilder() : null;
            } else {
              labelsBuilder_.addAllMessages(other.labels_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getConfigurationFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                PluginAdapter.Api.LabelOuterClass.Label m =
                    input.readMessage(
                        PluginAdapter.Api.LabelOuterClass.Label.parser(),
                        extensionRegistry);
                if (labelsBuilder_ == null) {
                  ensureLabelsIsMutable();
                  labels_.add(m);
                } else {
                  labelsBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * The adapter name uniquely identifies this adapter. Only one adapter is
       * allowed to connect with this name at a time.
       * It's useful to use this format: interface&#64;location. For example, if the
       * adapter is connected to the PRL42 System Under Test running at company Comp
       * and provides access to its SNMP interface, then the name would be
       * snmp&#64;prl42-comp.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The adapter name uniquely identifies this adapter. Only one adapter is
       * allowed to connect with this name at a time.
       * It's useful to use this format: interface&#64;location. For example, if the
       * adapter is connected to the PRL42 System Under Test running at company Comp
       * and provides access to its SNMP interface, then the name would be
       * snmp&#64;prl42-comp.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The adapter name uniquely identifies this adapter. Only one adapter is
       * allowed to connect with this name at a time.
       * It's useful to use this format: interface&#64;location. For example, if the
       * adapter is connected to the PRL42 System Under Test running at company Comp
       * and provides access to its SNMP interface, then the name would be
       * snmp&#64;prl42-comp.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The adapter name uniquely identifies this adapter. Only one adapter is
       * allowed to connect with this name at a time.
       * It's useful to use this format: interface&#64;location. For example, if the
       * adapter is connected to the PRL42 System Under Test running at company Comp
       * and provides access to its SNMP interface, then the name would be
       * snmp&#64;prl42-comp.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The adapter name uniquely identifies this adapter. Only one adapter is
       * allowed to connect with this name at a time.
       * It's useful to use this format: interface&#64;location. For example, if the
       * adapter is connected to the PRL42 System Under Test running at company Comp
       * and provides access to its SNMP interface, then the name would be
       * snmp&#64;prl42-comp.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private PluginAdapter.Api.ConfigurationOuterClass.Configuration configuration_;
      private com.google.protobuf.SingleFieldBuilderV3<
          PluginAdapter.Api.ConfigurationOuterClass.Configuration, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Builder, PluginAdapter.Api.ConfigurationOuterClass.ConfigurationOrBuilder> configurationBuilder_;
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       * @return Whether the configuration field is set.
       */
      public boolean hasConfiguration() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       * @return The configuration.
       */
      public PluginAdapter.Api.ConfigurationOuterClass.Configuration getConfiguration() {
        if (configurationBuilder_ == null) {
          return configuration_ == null ? PluginAdapter.Api.ConfigurationOuterClass.Configuration.getDefaultInstance() : configuration_;
        } else {
          return configurationBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public Builder setConfiguration(PluginAdapter.Api.ConfigurationOuterClass.Configuration value) {
        if (configurationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          configuration_ = value;
        } else {
          configurationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public Builder setConfiguration(
          PluginAdapter.Api.ConfigurationOuterClass.Configuration.Builder builderForValue) {
        if (configurationBuilder_ == null) {
          configuration_ = builderForValue.build();
        } else {
          configurationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public Builder mergeConfiguration(PluginAdapter.Api.ConfigurationOuterClass.Configuration value) {
        if (configurationBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            configuration_ != null &&
            configuration_ != PluginAdapter.Api.ConfigurationOuterClass.Configuration.getDefaultInstance()) {
            getConfigurationBuilder().mergeFrom(value);
          } else {
            configuration_ = value;
          }
        } else {
          configurationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public Builder clearConfiguration() {
        bitField0_ = (bitField0_ & ~0x00000002);
        configuration_ = null;
        if (configurationBuilder_ != null) {
          configurationBuilder_.dispose();
          configurationBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public PluginAdapter.Api.ConfigurationOuterClass.Configuration.Builder getConfigurationBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getConfigurationFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      public PluginAdapter.Api.ConfigurationOuterClass.ConfigurationOrBuilder getConfigurationOrBuilder() {
        if (configurationBuilder_ != null) {
          return configurationBuilder_.getMessageOrBuilder();
        } else {
          return configuration_ == null ?
              PluginAdapter.Api.ConfigurationOuterClass.Configuration.getDefaultInstance() : configuration_;
        }
      }
      /**
       * <pre>
       * Default configuration. All values should be set to their default values.
       * </pre>
       *
       * <code>.PluginAdapter.Api.Configuration configuration = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          PluginAdapter.Api.ConfigurationOuterClass.Configuration, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Builder, PluginAdapter.Api.ConfigurationOuterClass.ConfigurationOrBuilder> 
          getConfigurationFieldBuilder() {
        if (configurationBuilder_ == null) {
          configurationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              PluginAdapter.Api.ConfigurationOuterClass.Configuration, PluginAdapter.Api.ConfigurationOuterClass.Configuration.Builder, PluginAdapter.Api.ConfigurationOuterClass.ConfigurationOrBuilder>(
                  getConfiguration(),
                  getParentForChildren(),
                  isClean());
          configuration_ = null;
        }
        return configurationBuilder_;
      }

      private java.util.List<PluginAdapter.Api.LabelOuterClass.Label> labels_ =
        java.util.Collections.emptyList();
      private void ensureLabelsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          labels_ = new java.util.ArrayList<PluginAdapter.Api.LabelOuterClass.Label>(labels_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PluginAdapter.Api.LabelOuterClass.Label, PluginAdapter.Api.LabelOuterClass.Label.Builder, PluginAdapter.Api.LabelOuterClass.LabelOrBuilder> labelsBuilder_;

      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public java.util.List<PluginAdapter.Api.LabelOuterClass.Label> getLabelsList() {
        if (labelsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(labels_);
        } else {
          return labelsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public int getLabelsCount() {
        if (labelsBuilder_ == null) {
          return labels_.size();
        } else {
          return labelsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public PluginAdapter.Api.LabelOuterClass.Label getLabels(int index) {
        if (labelsBuilder_ == null) {
          return labels_.get(index);
        } else {
          return labelsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder setLabels(
          int index, PluginAdapter.Api.LabelOuterClass.Label value) {
        if (labelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelsIsMutable();
          labels_.set(index, value);
          onChanged();
        } else {
          labelsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder setLabels(
          int index, PluginAdapter.Api.LabelOuterClass.Label.Builder builderForValue) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.set(index, builderForValue.build());
          onChanged();
        } else {
          labelsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder addLabels(PluginAdapter.Api.LabelOuterClass.Label value) {
        if (labelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelsIsMutable();
          labels_.add(value);
          onChanged();
        } else {
          labelsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder addLabels(
          int index, PluginAdapter.Api.LabelOuterClass.Label value) {
        if (labelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelsIsMutable();
          labels_.add(index, value);
          onChanged();
        } else {
          labelsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder addLabels(
          PluginAdapter.Api.LabelOuterClass.Label.Builder builderForValue) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.add(builderForValue.build());
          onChanged();
        } else {
          labelsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder addLabels(
          int index, PluginAdapter.Api.LabelOuterClass.Label.Builder builderForValue) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.add(index, builderForValue.build());
          onChanged();
        } else {
          labelsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder addAllLabels(
          java.lang.Iterable<? extends PluginAdapter.Api.LabelOuterClass.Label> values) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, labels_);
          onChanged();
        } else {
          labelsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder clearLabels() {
        if (labelsBuilder_ == null) {
          labels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          labelsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public Builder removeLabels(int index) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.remove(index);
          onChanged();
        } else {
          labelsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public PluginAdapter.Api.LabelOuterClass.Label.Builder getLabelsBuilder(
          int index) {
        return getLabelsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public PluginAdapter.Api.LabelOuterClass.LabelOrBuilder getLabelsOrBuilder(
          int index) {
        if (labelsBuilder_ == null) {
          return labels_.get(index);  } else {
          return labelsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public java.util.List<? extends PluginAdapter.Api.LabelOuterClass.LabelOrBuilder> 
           getLabelsOrBuilderList() {
        if (labelsBuilder_ != null) {
          return labelsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(labels_);
        }
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public PluginAdapter.Api.LabelOuterClass.Label.Builder addLabelsBuilder() {
        return getLabelsFieldBuilder().addBuilder(
            PluginAdapter.Api.LabelOuterClass.Label.getDefaultInstance());
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public PluginAdapter.Api.LabelOuterClass.Label.Builder addLabelsBuilder(
          int index) {
        return getLabelsFieldBuilder().addBuilder(
            index, PluginAdapter.Api.LabelOuterClass.Label.getDefaultInstance());
      }
      /**
       * <pre>
       * Labels that this adapter supports.
       * </pre>
       *
       * <code>repeated .PluginAdapter.Api.Label labels = 3;</code>
       */
      public java.util.List<PluginAdapter.Api.LabelOuterClass.Label.Builder> 
           getLabelsBuilderList() {
        return getLabelsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PluginAdapter.Api.LabelOuterClass.Label, PluginAdapter.Api.LabelOuterClass.Label.Builder, PluginAdapter.Api.LabelOuterClass.LabelOrBuilder> 
          getLabelsFieldBuilder() {
        if (labelsBuilder_ == null) {
          labelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PluginAdapter.Api.LabelOuterClass.Label, PluginAdapter.Api.LabelOuterClass.Label.Builder, PluginAdapter.Api.LabelOuterClass.LabelOrBuilder>(
                  labels_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          labels_ = null;
        }
        return labelsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PluginAdapter.Api.Announcement)
    }

    // @@protoc_insertion_point(class_scope:PluginAdapter.Api.Announcement)
    private static final PluginAdapter.Api.AnnouncementOuterClass.Announcement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PluginAdapter.Api.AnnouncementOuterClass.Announcement();
    }

    public static PluginAdapter.Api.AnnouncementOuterClass.Announcement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Announcement>
        PARSER = new com.google.protobuf.AbstractParser<Announcement>() {
      @java.lang.Override
      public Announcement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Announcement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Announcement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PluginAdapter.Api.AnnouncementOuterClass.Announcement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PluginAdapter_Api_Announcement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PluginAdapter_Api_Announcement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022announcement.proto\022\021PluginAdapter.Api\032" +
      "\023configuration.proto\032\013label.proto\"\177\n\014Ann" +
      "ouncement\022\014\n\004name\030\001 \001(\t\0227\n\rconfiguration" +
      "\030\002 \001(\0132 .PluginAdapter.Api.Configuration" +
      "\022(\n\006labels\030\003 \003(\0132\030.PluginAdapter.Api.Lab" +
      "elb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PluginAdapter.Api.ConfigurationOuterClass.getDescriptor(),
          PluginAdapter.Api.LabelOuterClass.getDescriptor(),
        });
    internal_static_PluginAdapter_Api_Announcement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PluginAdapter_Api_Announcement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PluginAdapter_Api_Announcement_descriptor,
        new java.lang.String[] { "Name", "Configuration", "Labels", });
    PluginAdapter.Api.ConfigurationOuterClass.getDescriptor();
    PluginAdapter.Api.LabelOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
